# Primero nuestro análisis de los datos
Aqui haré mi filtrado y visualizacion, luego ya la pasaré al .py

In [1]:
import pandas as pd
import matplotlib as pb

In [2]:
df = pd.read_csv("/home/maylinanzures/ejercicio5/TukeyIAProyect/AI_Student_Life_Pakistan_2026.csv")

In [3]:
df.head(5)

,Student_ID,Age,Gender,Education_Level,City,AI_Tool_Used,Daily_Usage_Hours,Purpose,Impact_on_Grades,Satisfaction_Level
0,1,15,Female,School,Lahore,ChatGPT,0.8,Writing,Slight Decline,Low
1,2,15,Female,College,Multan,Copilot,1.6,Learning,No Change,High
2,3,16,Female,College,Multan,ChatGPT,1.8,Research,Improved,Low
3,4,22,Male,University,Karachi,ChatGPT,4.2,Learning,Improved,High
4,5,16,Male,School,Multan,ChatGPT,1.8,Coding,Improved,Medium

El componente visual: Crea un gráfico de barras (o barras apiladas) que muestre la proporción del impacto en las notas (Impact_on_Grades) segmentado por herramienta de IA (AI_Tool_Used).

La interactividad: Agrega un menú desplegable (st.selectbox) que permita al usuario filtrar la vista por Ciudad (City). Debe incluir una opción de "Todas las ciudades" para ver el panorama general.

In [4]:
df_IA = df.groupby('AI_Tool_Used')[['Impact_on_Grades']].value_counts(normalize=True).unstack()
df_IA
# sacamos los paises muejeje
df_pais = df['City'].value_counts()
lista_paises= df_pais.index
lista_paises

Index(['Multan', 'Lahore', 'Islamabad', 'Faisalabad', 'Karachi'], dtype='str', name='City')

Comparativa de Propósitos: Coding vs. Writing (Selectores de Opciones)
El componente visual: Un gráfico que muestre cómo cambian las notas de los estudiantes dependiendo de para qué usan la IA (Purpose).

La interactividad: Usa botones de opción de selección única (st.radio) para que el usuario pueda alternar rápidamente entre los distintos propósitos de uso (ej. Coding, Writing, Research). El gráfico debe actualizarse para mostrar solo los datos del propósito seleccionado.

In [5]:
#para el selecbox ocupamos las option en lista (iterable):3
df_P = df['Purpose'].value_counts()
listaCvsW = df_pais.index

#como cambian las notas dependiendo de para que usan la IA
df_Notas = df.groupby('Purpose')[['Impact_on_Grades']].value_counts().unstack()
df_Notas

Impact_on_Grades  Improved  No Change  Slight Decline
Purpose
Coding                  11          5               4
Homework                 9         10               5
Learning                 9          4               8
Research                 7          7               7
Writing                  3          8               3

3. Análisis de Anomalías: Alta Satisfacción, Notas en Declive (Filtros Numéricos)
El componente visual: Hay usuarios con un nivel de satisfacción Alto (High) pero con impacto negativo en sus notas (Slight Decline). Muestra cuántos son y una tabla de datos (st.dataframe) detallando qué herramientas usan principalmente estos estudiantes.

La interactividad: Incorpora un control deslizante (st.slider) que filtre esta tabla interactiva con base en las horas de uso diario (Daily_Usage_Hours), para observar si las horas de uso influyen en esta anomalía.

In [37]:
#filtrar a los de alta satisfaccion, notas en declive, [[]] al final es para guardar solo las columnas que quieras
dfAS_ND = df[(df['Satisfaction_Level'] == 'High') & (df['Impact_on_Grades'] == 'Slight Decline')][['Satisfaction_Level', 'Impact_on_Grades', 'AI_Tool_Used','Daily_Usage_Hours']]
dfAS_ND